[programs.localnet]
formfn_auction_house = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
formfn_auction_house = "devmBQyHHBPiLcuCqbWWRYxCG33ntAfPD5nXZeLd4eX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "keys/devnet/deployer-keypair.json"

# Token Metadata
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "artifacts/mpl_token_metadata.so"

[scripts]
test = "./scripts/run-tests.sh"
